model:
  name: "resnet50"
  num_classes: 1000
  print_summary: False
  print_model: False
  
data:
  batch_size: 256
  num_workers: 8
  dataset: "imagenet"
  root_dir: "./data/imagenet"
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  
transforms:
  resize: 
    height: 224
    width: 224
  center_crop:
    height: 224
    width: 224
  horizontal_flip_prob: 0.5
  shift_scale_rotate:
    shift_limit: 0.1
    scale_limit: 0.1
    rotate_limit: 15
    p: 0.5
  coarse_dropout:
    max_holes: 8
    max_height: 16
    max_width: 16
    p: 0.5
    
training:
  epochs: 90
  lr_finder:
    enabled: False
    start_lr: 0.0001
    end_lr: 10
    num_iter: 100
  optimizer:
    name: 'sgd'
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0001
  scheduler:
    name: 'onecycle'
    max_lr: 0.1  # This will be found using lr_finder
    pct_start: 0.3
    div_factor: 10
    final_div_factor: 100 